name: Publish to NPM

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      - name: Run tests
        # some browsers may need a display to work properly
        # create a virtual one and route its output to /dev/null
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          yarn test


  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      - name: Create build
        run: yarn build

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo --branches main
