name: Lint and test PR

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run tests
        # some browsers may need a display to work properly
        # create a virtual one and route its output to /dev/null
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          yarn test

      # Check whether build still works smoothly
      - name: Create build
        run: yarn build

      # Check if docs are complete and can be built
      - name: Create docs
        run: yarn docs

      # Perform release dry run when the PR is targeting main
      - name: Release dry run
        if: ${{ github.ref_name != 'develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo --dry-run --branches main

