name: Build and update docs

on:
  push:
    branches:
      - develop

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      # Packages need to be built for doc generation
      - name: Create build
        run: yarn build

      - name: Create docs
        run: yarn docs

      # Since the branch is protected, create a PR for merging the doc updates
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "docs: auto-update based on code changes"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: feature/docs/auto-update
          delete-branch: true
          branch-suffix: timestamp
          add-paths: |
            docs/*.md
          title: "Update docs based on changes in develop"
          body: |
            Automated pull request containing documentation-specific updates
            resulting from changes to the `develop` branch."
          assignees: johh
